export const data = [
  {
    id: 1,
    nameProduct: "Cannoli",
    category: "Postre",
    image: "https://images.hola.com/imagenes/cocina/recetas/20220224205246/cannonli-pistachos-chocolate/1-55-149/cannoli-adobe-m.jpg",
    flavor: "{[Chips de Chocolate, Naranja Caramelizado, Pistacho, Vainilla]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "40.000",
    quantity: "30",
  },
  {
    id: 2,
    nameProduct: "Tiramisu",
    category: "Postre",
    image: "https://comidaitaliana.online/wp-content/uploads/2022/10/receta-de-tiramisu.jpg",
    flavor: "{[Cafe, Frutos rojos , Caramelo, Matcha]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "35.000",
    quantity: "30",
  },
  {
    id: 3,
    nameProduct: "Sfogliatelle",
    category: "Postre",
    image: "https://i0.wp.com/grandprixeats.com/wp-content/uploads/2021/04/sfogliatelle_grandprixeats.jpg?fit=750%2C1000&ssl=1",
    flavor: "{[Relleno crema pastelera,Relleno nutella , Relleno arequipe, ]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price: "10.000",    
    quantity: "30",
  },
  {
    id: 4,
    nameProduct: "Gelato",
    category: "Postre",
    image: "https://www.recetasnestle.com.co/sites/default/files/styles/crop_article_banner_desktop_nes/public/2023-04/gelato-el-famoso-helado-italiano.jpg?itok=EfOJOLww",
    flavor: "{[flavor de tu preferencia]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "18.000",
    quantity: "30",
  },
  {
    id: 5,
    nameProduct: "Helado",
    category: "Postre",
    image: "https://images.squarespace-cdn.com/content/v1/55195f4de4b06fca171948ba/1442946836126-H1RA20FCS0QNT1W5OI6Z/home+pic.jpg?format=2500w",
    flavor: "{[flavor de tu preferencia]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "25.000",
    quantity: "30",
  },
  {
    id: 6,
    nameProduct: "Zuccotto",
    category: "Pasteles",
    image: "https://img.taste.com.au/z0Jw1bB2/taste/2016/11/zuccotto-80739-1.jpeg",
    flavor: "{[Chocolate,limon, Fresa, Cafe]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "50.000",
    quantity: "30",
  },
  {
    id: 7,
    nameProduct: "Genovesa",
    category: "Pasteles",
    image: "https://boquisabroso.com.co/wp-content/uploads/2023/02/Receta-de-Torta-Genovesa.jpg",
    flavor: "{[Red Velvet, Chocolatosa, Mora silvestre, Baileys]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "50.000",
    quantity: "30",
  },
  {
    id: 8,
    nameProduct: "Crostata",
    category: "Pasteles",
    image: "https://thegastromagazine.com/wp-content/uploads/2022/11/crostata-di-marmellata-LuCake-How-To-Make-Crostata-One-Of-Italys-Most-Underrated-Desserts.jpg",
    flavor: "{[Fresa, limon, Maracuya, Mora]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "47.000",
    quantity: "30",
  },
  {
    id: 9,
    nameProduct: "Pastiera",
    category: "Pasteles",
    image: "https://www.recetas-italia.com/base/stock/Recipe/216-image/216-image_web.jpg.webp",
    flavor: "{[Napolitana]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "40.000",
    quantity: "30",
  },
  {
    id: 10,
    nameProduct: "Caprese",
    category: "Pasteles",
    image: "https://images.food52.com/aI7uDoVTvI6WO5-Snj5yH_N3xRc=/2016x1344/filters:format(webp)/481ebb23-8b48-4b53-9fe2-8ab6079d17a0--torta-caprese-IMG_6024.jpg",
    flavor: "{[Almendra y chocolate]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "57.000",
    quantity: "30",
  },
  {
    id: 11,
    nameProduct: "Girellas",
    category: "Pasabocas",
    image: "https://www.lopezaragon.com/wp-content/uploads/2015/05/ReposteriaCreativa-Girellas.jpg",
    flavor: "{[Mermelada mora, fresa,uva,maracuya]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "18.000",
    quantity: "30",
  },
  {
    id: 12,
    nameProduct: "Arancini",
    category: "Pasabocas",
    image: "https://i3.wp.com/lmld.org/wp-content/uploads/2016/08/arancini-3-1.jpg",
    flavor: "{[Rellenos de queso, arroz y jamon ]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price: "16.000",
    quantity: "30",
  },
  {
    id: 13,
    nameProduct: "Grissinis",
    category: "Pasabocas",
    image: "https://us.123rf.com/450wm/gingagi/gingagi2207/gingagi220700109/189794179-palitos-de-grisines-caseros-patata-grissini-merienda-saludable.jpg?ver=6",
    flavor: "{[Bastones de pan crujientes]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "20.000",
    quantity: "30",
  },
  {
    id: 14,
    nameProduct: "Volovanes",
    category: "Pasabocas",
    image: "https://placeralplato.com/files/2016/02/Vol-au-vent.jpg",
    flavor: "{[Pollo, Atun, camaron, Frutas]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "18.000",
    quantity: "30",
  },
  {
    id: 15,
    nameProduct: "Quibes",
    category: "Pasabocas",
    image: "https://ifolha.temmais.com/wp-content/uploads/2023/05/SUPERAPETITE-1-16-05-23.jpg",
    flavor: "{[Carne y pollo]}",
    Tamaño: "{[Pequeño, Mediano]}",
    price:  "17.500",
    quantity: "30",
  },
  {
    id: 16,
    nameProduct: "Grappa",
    category: "Bebida",
    image: "https://img.freepik.com/fotos-premium/bebida-italiana-grappa-dorada-sobre-fondo-madera_123827-18442.jpg",
    flavor: "{Uva]}",
    price: "15.000",
    quantity: "30",
  },
  {
    id: 17,
    nameProduct: "Marrasquino",
    category: "Bebida",
    image: "https://bodegasalianza.vteximg.com.br/arquivos/ids/182859-800-800/30855_1.jpg?v=637538417341000000",
    flavor: "{[Cereza]}",
    price: "12.000",
    quantity: "30",
  },
  {
    id: 18,
    nameProduct: "Sambuca",
    category: "Bebida",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2LNxo-Gl73MmHJso72Qdyu6_8GdMz2A6lfQ&usqp=CAU",
    flavor: "{[licor de anis]}",
    price: "17.000",
    quantity: "30",
  },
  {
    id: 19,
    nameProduct: "Prosecco",
    category: "Bebida",
    image: "https://cigarreriareal.com/wp-content/uploads/2020/09/00653.jpg",
    flavor: "{[vino blanco]}",
    price: "9000",
    quantity: "30",
  },
];
